import fs from 'fs';
import path from 'path';

const DIST_DIR = './dist';
const SRC_DIR = './src';
const SPRITE_PATH = path.join(DIST_DIR, 'sprite.svg');
const OUTPUT_PATH = path.join(DIST_DIR, 'index.html');

async function generateDemo() {
  try {
    // Read the sprite content to inline it
    const spriteContent = fs.readFileSync(SPRITE_PATH, 'utf8');
    
    // Get all icon names from the src directory
    const icons = fs.readdirSync(SRC_DIR)
      .filter(file => file.endsWith('.svg'))
      .map(file => path.parse(file).name);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SVG Sprite Gallery</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #0f172a;
            --card-bg: #1e293b;
            --text-color: #f1f5f9;
            --accent-color: #38bdf8;
            --border-color: #334155;
            --icon-color: #94a3b8;
        }

        body {
            font-family: 'Outfit', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            margin: 0;
            padding: 40px 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        header {
            text-align: center;
            margin-bottom: 60px;
            max-width: 800px;
        }

        h1 {
            font-size: 3rem;
            font-weight: 600;
            margin-bottom: 10px;
            background: linear-gradient(to right, #38bdf8, #818cf8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        p {
            color: var(--icon-color);
            font-size: 1.1rem;
        }

        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
            gap: 24px;
            width: 100%;
            max-width: 1200px;
        }

        .card {
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 16px;
            padding: 24px;
            display: flex;
            flex-direction: column;
            align-items: center;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            cursor: pointer;
            position: relative;
            overflow: hidden;
        }

        .card:hover {
            transform: translateY(-8px);
            border-color: var(--accent-color);
            box-shadow: 0 10px 25px -5px rgba(56, 189, 248, 0.2);
        }

        .icon-wrapper {
            width: 64px;
            height: 64px;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 16px;
            color: var(--icon-color);
            transition: color 0.3s ease;
        }

        .card:hover .icon-wrapper {
            color: var(--accent-color);
        }

        svg.icon {
            width: 100%;
            height: 100%;
        }

        .name {
            font-size: 0.9rem;
            font-weight: 400;
            color: var(--text-color);
            text-align: center;
            word-break: break-all;
        }

        .copy-hint {
            position: absolute;
            bottom: -20px;
            font-size: 0.7rem;
            color: var(--accent-color);
            transition: bottom 0.3s ease;
        }

        .card:hover .copy-hint {
            bottom: 8px;
        }

        /* Sprite is hidden */
        #sprite-container {
            display: none;
        }

        footer {
            margin-top: 80px;
            color: var(--icon-color);
            font-size: 0.8rem;
        }
    </style>
</head>
<body>

    <div id="sprite-container">
        ${spriteContent}
    </div>

    <header>
        <h1>SVG Sprite Gallery</h1>
        <p>A collection of ${icons.length} optimized icons, ready to use in your project.</p>
    </header>

    <div class="grid">
        ${icons.map(name => `
        <div class="card" onclick="copyToClipboard('${name}')">
            <div class="icon-wrapper">
                <svg class="icon">
                    <use href="#${name}"></use>
                </svg>
            </div>
            <div class="name">${name}</div>
            <div class="copy-hint">Click to copy ID</div>
        </div>
        `).join('')}
    </div>

    <footer>
        Generated by SVG Optimizer & Spriter
    </footer>

    <script>
        function copyToClipboard(name) {
            const text = '<svg><use href="dist/sprite.svg#' + name + '"></use></svg>';
            navigator.clipboard.writeText(text).then(() => {
                alert('Code snippet copied to clipboard: ' + text);
            });
        }
    </script>
</body>
</html>`;

    fs.writeFileSync(OUTPUT_PATH, html);
    console.log('✨ Premium demo page generated at dist/index.html');
  } catch (err) {
    console.error('❌ Error generating demo:', err);
  }
}

generateDemo();
